<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="JAMESBOND007" failures="1" tests="1" name="Default test(failed)" time="0.121" errors="0" timestamp="2023-04-10T09:53:40 IST">
  <testcase classname="testNG.TestCase2" name="testMethod1" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testNG.TestCase2.testMethod1(TestCase2.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase classname="testNG.TestCase2" name="testMethod" time="0.0">
    <ignored/>
  </testcase> <!-- testMethod -->
</testsuite> <!-- Default test(failed) -->
